# -------------------------------------------------------------------
# Codehaus CARGO, copyright 2004-2011 Vincent Massol, 2012-2021 Ali Tokmen.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -------------------------------------------------------------------

version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          - dependency_name: "commons-discovery:commons-discovery"
          - dependency_name: "javax.mail:mail"
          - dependency_name: "javax.servlet:servlet-api"
          - dependency_name: "junit:junit"
            versions: ["4.x"]
          - dependency_name: "org.apache.ant:ant"
            versions: ["1.10.x"]
          - dependency_name: "org.apache.derby:derby"
            versions: ["10.13.x", "10.14.x", "10.15.x"]
          - dependency_name: "org.apache.maven:maven-archiver"
          - dependency_name: "org.apache.maven:maven-core"
          - dependency_name: "org.apache.maven:maven-plugin-api"
          - dependency_name: "org.apache.maven:maven-settings"
          - dependency_name: "org.apache.maven.plugin-tools:maven-plugin-annotations"
          - dependency_name: "org.jdom:jdom"
            versions: ["2.x"]
          - dependency_name: "org.osgi:org.osgi.core"
          - dependency_name: "org.springframework:spring"
